server:
  port: 8888
  
spring:
  application:
    name: appconfig-manager
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
---
spring:
  profiles: local

---
spring:
  profiles: dev
       
---    
spring:
  profiles: ist
    
---    
spring:
  profiles: uat
  
---    
spring:
  profiles: nft
    
---    
spring:
  profiles: prod